[package]
name = "pyproject-toml-rs-mwe"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pyproject-toml = "0.3.3"
toml_edit = "0.19.7"
